# Site settings
baseurl = "http://hatajoe.github.io/blog/"
languageCode = "ja-jp"
title = "hatajoe"
theme = "hugo-cactus-theme"

[params]
	name = "Hatajoe's blog"
	description = "Yusuke Hatanaka(a.k.a Hatajoe)'s blog"
	bio = "Blogger - Programmer - Little Gopher"
	# Enter optionally your twitter account
	twitter = "Hatajoe"
	# Disable comments by leaving disqusShortname empty
	disqusShortname = "hatajoe"
	# Enter your tracking code to enable Google Analytics
	googleAnalytics = "UA-67714030-1"
	enableRSS = true

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "Blogger - Programmer - Little Gopher"
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""
